name: Ubuntu RDP via GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop Environment & RDP
        run: |
          sudo apt update && sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "xfce4-session" > ~/.xsession
          sudo useradd -m ubuntuRDP && echo 'ubuntuRDP:Pass1234' | sudo chpasswd
          sudo usermod -aG sudo ubuntuRDP

      - name: Create Serveo SSH Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net > serveo.log 2>&1 &
          sleep 5
          cat serveo.log
